Add reflectometry logo
scipp/essreflectometry pull request #20
Opened 2023-12-12 09:06 UTC by jokasimr

2023-12-12 09:10 UTC, jl-wynen commented on docs/_static/favicon.ico
You can actually use an SVG as favicon now. Have a look at essdiffraction.

2023-12-12 09:10 UTC, jl-wynen commented on docs/_static/logo-dark.svg
Why did you abbreviate the name? We decided earlier that we use the full name in the logo. But you may need to reduce the font size, see essdiffraction.

2023-12-12 09:11 UTC, jokasimr commented on docs/_static/logo-dark.svg
It looks abbreviated but it contains the whole name. I think it is just how github displays svgs

2023-12-12 09:12 UTC, jl-wynen commented on docs/_static/logo-dark.svg
The problem is that the page does not include the whole logo:
![logo-size](https://github.com/scipp/essreflectometry/assets/11393224/76cc7a0e-8547-4734-a7dc-da8041dda4e6)

2023-12-12 09:20 UTC, jokasimr commented on docs/_static/logo-dark.svg
Okay, I don't know enough svg. I saw that the esssans logo also [looks cut off](https://github.com/scipp/esssans/blob/main/resources/logo.svg) but it displays fine [in the docs](https://scipp.github.io/esssans/).

2023-12-12 09:35 UTC, jokasimr commented
![Screenshot from 2023-12-12 10-34-59](https://github.com/scipp/essreflectometry/assets/20954731/99a94099-358a-44ae-85ea-3a076be951eb)
This is what it looks like in the browser. Looks good to me!

2023-12-12 09:38 UTC, jl-wynen approved these changes

2023-12-12 10:58 UTC, SimonHeybrock commented on docs/_static/logo-dark.svg
I think this may be due to a page-size setting. Did you store as a plain svg, or an Inkscape svg? Not sure that is the cause, but we should use plain svg.

2023-12-12 11:45 UTC, jl-wynen commented on docs/_static/logo-dark.svg
The page size was set incorrectly. It is fixed in the latest version.

2023-12-12 11:57 UTC, SimonHeybrock requested changes
Looks like the wrong font to me (in the built docs screenshot).

2023-12-13 08:35 UTC, jokasimr commented
> Looks like the wrong font to me (in the built docs screenshot).

Yes the path version looks different than the text-version, I don't know why. :thinking: 

This is the command I used to create the path-versions in `docs/_static`:
```inkscape --export-text-to-path -o docs/_static/logo-dark.svg resources/logo.svg```

2023-12-13 12:06 UTC, jokasimr commented
It seems esssans has the same font issue. 
![Screenshot from 2023-12-13 13-05-52](https://github.com/scipp/essreflectometry/assets/20954731/530b8b84-f147-455b-bfc4-58678562c25a)
Compare to the logo using the right font [here](https://github.com/scipp/esssans/blob/main/resources/logo.svg)

2023-12-14 07:21 UTC, SimonHeybrock commented
> It seems esssans has the same font issue. ![Screenshot from 2023-12-13 13-05-52](https://private-user-images.githubusercontent.com/20954731/290183544-530b8b84-f147-455b-bfc4-58678562c25a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Mzg2ODUsIm5iZiI6MTcwMjUzODM4NSwicGF0aCI6Ii8yMDk1NDczMS8yOTAxODM1NDQtNTMwYjhiODQtZjE0Ny00NTViLWJmYzQtNTg2Nzg1NjJjMjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA3MTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZmRiODI0OGZhNjBhN2Q0YzA1NmU3ZGNkYjVlNWVmM2IwMDkyN2UyM2IwNmM4MTI3YTRjNDE3Yzc0NGE5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.41R0x4X8D-1XoJgdO9IsG08o1Y2siBqOXNaW5oQbeOI) Compare to the logo using the right font [here](https://github.com/scipp/esssans/blob/main/resources/logo.svg)

Looks ok to me? The Reflectometry docs screenshot you posted looks very different.

2023-12-14 07:22 UTC, SimonHeybrock commented
> > Looks like the wrong font to me (in the built docs screenshot).
> 
> Yes the path version looks different than the text-version, I don't know why. 🤔
> 
> This is the command I used to create the path-versions in `docs/_static`: `inkscape --export-text-to-path -o docs/_static/logo.svg resources/logo.svg`

I don't think the command matters necessarily, but whether you have to correct font installed?

2023-12-14 08:02 UTC, jl-wynen commented
> > It seems esssans has the same font issue. ![Screenshot from 2023-12-13 13-05-52](https://private-user-images.githubusercontent.com/20954731/290183544-530b8b84-f147-455b-bfc4-58678562c25a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Mzg2ODUsIm5iZiI6MTcwMjUzODM4NSwicGF0aCI6Ii8yMDk1NDczMS8yOTAxODM1NDQtNTMwYjhiODQtZjE0Ny00NTViLWJmYzQtNTg2Nzg1NjJjMjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA3MTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZmRiODI0OGZhNjBhN2Q0YzA1NmU3ZGNkYjVlNWVmM2IwMDkyN2UyM2IwNmM4MTI3YTRjNDE3Yzc0NGE5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.41R0x4X8D-1XoJgdO9IsG08o1Y2siBqOXNaW5oQbeOI) Compare to the logo using the right font [here](https://github.com/scipp/esssans/blob/main/resources/logo.svg)
> 
> Looks ok to me? The Reflectometry docs screenshot you posted looks very different.

The logo and screenshot look the same to me. I guess neither Johannes nor I have the correct font installed?

2023-12-14 08:31 UTC, SimonHeybrock approved these changes

2023-12-14 09:18 UTC, merged